### ISSUE TITLE
metaX installation problems

### ISSUE THREAD

**Issue by educhicano** [wenbostar/metaX#1]
Dear Bo Wen,
First of all, let me congratulate you for this awesome work.
I’m trying to use your R package, metaX but, unfortunately I was unable to install it neither in Windows nor in OSX. 
It gives me the following errors in windows (10, professional ed, using RStudio):
Installing package into ‘C:/Users/Eduardo Chicano/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'metaX' ...
** R
** inst
** preparing package for lazy loading
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/Eduardo Chicano/Documents/R/win-library/3.4/mvtnorm/libs/x64/mvtnorm.dll':
  `maximal number of DLLs reached...
ERROR: lazy loading failed for package 'metaX'
* removing 'C:/Users/Eduardo Chicano/Documents/R/win-library/3.4/metaX'
* restoring previous 'C:/Users/Eduardo Chicano/Documents/R/win-library/3.4/metaX'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Eduardo Chicano\Documents\R\win-library\3.4" "C://metaX_1.4.16.tar"' had status 1
Warning in install.packages :
  installation of package ‘C://metaX_1.4.16.tar’ had non-zero exit status

These are the messages from console when I try to install in OSX (10.13 macOS High Sierra), also with R 3.4.2 and RStudio: 

> install.packages("metaX_1.4.16.tar.gz",repos=NULL,type="source")
Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'default/Europe/Madrid'
* installing *source* package ‘metaX’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgl/libs/rgl.so
  Reason: Incompatible library version: rgl.so requires version 5.0.0 or later, but libGLU.1.dylib provides version 1.3.0
ERROR: lazy loading failed for package ‘metaX’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/metaX’
Warning in install.packages :
  installation of package ‘metaX_1.4.16.tar.gz’ had non-zero exit status

What am I doing wrong? I’m currently using R 3.4.2, and I have installed all dependencies required for your package.
I’m planning to use this package with Maldi Imaging lipidomics data but I have the data in metaboanalyst format (.csv). As far as I have read, this package loads this csv without problems, isn’t it?
Thanks in advance!
Best regards

**Comment by wenbostar** [comment]
Hi @educhicano , I'm sorry for the late reply. In Windows system, you can add the following environment variable to your system:

![image](https://user-images.githubusercontent.com/5302110/33292856-55ba0c50-d390-11e7-980a-130aeda3f9af.png)

Please let me know if it works.

Bo

**Comment by educhicano** [comment]
Hi Bo,
yes, it works!
Thanks!!!!

**Comment by wenbostar** [comment]
Great, please feel free to let me know if you have any new questions.
