### ISSUE TITLE
No installation support: bioconductor has marked as deprecated

### ISSUE THREAD

**Issue by tbrunetti** [wenbostar/metaX#11]
metaX can no longer be installed on R 3.2 or greater.  It looks like the package dependency mixOmics is only supported on R versions 3.5, however metaX is only supported on R version 3.2, therefore due to the higher mixOmics package dependency metaX cannot be installed on any versions of R.  

Is there any plan to resolve this in the near future?

**Comment by wenbostar** [comment]
The latest version of metaX in github (https://github.com/wenbostar/metaX/) supports R version 3.5. I didn't submit the latest version to bioconductor. You can install the latest version of metaX through the following method:

```r
# Install the development version from GitHub:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("wenbostar/metaX")
```

Please feel free to let me know if you have any other questions.

**Comment by tbrunetti** [comment]
Thank you for your reply.  I tried the above prior to opening the issue without any luck, but I will try it again.

**Comment by wenbostar** [comment]
Please let me know what error you got.

**Comment by arehartc** [comment]
I have the same problem as tbrunetti, using your instructions above I get the following error:

`* installing *source* package ‘ModelMetrics’ ...
** package ‘ModelMetrics’ successfully unpacked and MD5 sums checked
** libs
/usr/bin/clang++  -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/chris/Library/R/3.5/library/Rcpp/include" -I/opt/local/include -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -fPIC  -pipe -Os -stdlib=libc++ -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -arch x86_64  -c RcppExports.cpp -o RcppExports.o
/usr/bin/clang++  -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/chris/Library/R/3.5/library/Rcpp/include" -I/opt/local/include -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -fPIC  -pipe -Os -stdlib=libc++ -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -arch x86_64  -c auc_.cpp -o auc_.o
auc_.cpp:2:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [auc_.o] Error 1
ERROR: compilation failed for package ‘ModelMetrics’
* removing ‘/Users/chris/Library/R/3.5/library/ModelMetrics’
Error in i.p(...) : 
  (converted from warning) installation of package ‘ModelMetrics’ had non-zero exit status`

**Comment by wenbostar** [comment]
@arehartc , great, thanks for your update.
