### ISSUE TITLE
Error in peakStat: object 'pcaColor' not found

### ISSUE THREAD

**Issue by arehartc** [wenbostar/metaX#12]
Bo,

Thank you so much for your software and continual support to keep it running.  I am trying to run the software on your test data (and my own data) and cannot seem to get past the following error message.  Might you be able to help?

```
plot PCA for value 'valueNorm'
scaling in PCA: none 
centering in PCA: FALSE 
change in estimate:  0 


Bhattacharyya distance matrix:
           [,1]       [,2]       [,3]       [,4]
[1,] 0.00000000 0.86499144 0.67873091 0.06768484
[2,] 0.86499144 0.00000000 0.03060409 0.37393193
[3,] 0.67873091 0.03060409 0.00000000 0.25861844
[4,] 0.06768484 0.37393193 0.25861844 0.00000000
Mean of the Bhattacharyya distance:
[1] 0.3790936
Error in peakStat(para = para, plsdaPara = plsdaPara, doROC = doROC, pcaLabel = pcaLabel,  : 
  object 'pcaColor' not found
```

**Comment by wenbostar** [comment]
Hi @arehartc, thanks for using metaX. There is a bug for parameter name. I just fixed that and updated the code. Could you please update metaX package and run you code again? Please let me know if it works.

**Comment by arehartc** [comment]
Works perfectly now. Thank you so much!!

**Comment by wenbostar** [comment]
Great.
