### ISSUE TITLE
metaX plotting functions?

### ISSUE THREAD

**Issue by seb951** [wenbostar/metaX#15]
Hi, 

Is there a away to modify your plotting functions (e.g. plotTreeMap, plotPCA) such that they output to the current active graphing device instead of directly outputting to a file?

It is not proper R standard to directly output to a graph, because it doesn't allow the user to do any modifications to the graph.

thank you,

**Comment by wenbostar** [comment]
I can update the functions to do that. Which plotting functions do you need to have this function?

Bo

**Comment by seb951** [comment]
Thanks for your quick answer. Quite frankly, I don't know right now.

You seem to have one function [ metaXpipe() ] that does everything, but it's really hard to understand what is done exactly with the current documentation (?metaXpipe) and example (metaX_demo.R).

Typically, a flexible pipeline will go through a set of steps (such as nicely outlined in Figure1 of your paper) to generate outputs (multivariate statistics analyses, network analyses, etc) in the form of R objects which can then be used as input to generate graphics in the current R graphing device. metaXpipe does not seem to generate any R object:
p <- metaXpipe(para,plsdaPara=plsdaPara)
p
Error: object 'p' not found

Will look into it more deeply in the next few days.

**Comment by wenbostar** [comment]
I'm updating metaX and a new version will be released in the next few weeks. At that time, you will have an HTML report with detailed information about what has been done for each metaXpipe run.
