### ISSUE TITLE
Warning in R ver. 3.4.3 when install xcms

### ISSUE THREAD

**Issue by Tang17** [wenbostar/metaX#2]
Dear Wen,
First, thanks for your sharing of metaX. 
When run install packages,
install.packages(c("Nozzle.R1","ggplot2","parallel","reshape2","plyr","BBmisc","mixOmics","missForest","doParallel","DiscriMiner","xcms","ape","scatterplot3d","pheatmap","bootstrap","boot","caret","dplyr","stringr","RColorBrewer","DiffCorr","RCurl","lattice","data.table","igraph","tidyr","scales","VennDiagram","pROC","readr","e1071","randomForest","coop","fpc","ROCR"))
The following warning presented: 
"Warning messages:
1: packages ‘parallel’, ‘xcms’ are not available (for R version 3.4.3) 
2: package ‘parallel’ is a base package, and should not be updated "
when running:
biocLite(c("pcaMethods","vsn","pls","faahKO","mzR","preprocessCore","impute","CAMERA","ropls","sva","SSPA"))
The following warning presented: 
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\TANG Zhi\Documents\R\win-library\3.4" C:\Users\TANGZH~1\AppData\Local\Temp\RtmpqEeOw3/downloaded_packages/faahKO_1.18.0.tar.gz' had status 1 
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘faahKO’ had non-zero exit status

How to resolve these problems? Thanks for your help in advance.

**Comment by wenbostar** [comment]
Hi @Tang17 , Could you please try to download XCMS and faahKO package manually using the following links?

http://bioconductor.org/packages/release/bioc/bin/windows/contrib/3.4/xcms_3.0.0.zip
http://bioconductor.org/packages/devel/data/experiment/src/contrib/faahKO_1.19.0.tar.gz

After you download the two packages, then please install them using the following R code:

```shell
R CMD INSTALL xcms_3.0.0.zip
R CMD INSTALL faahKO_1.19.0.tar.gz
```

Please let me know if it works.

**Comment by Tang17** [comment]
xcms has been successfully installed. but for the faahKO, it does not work.
the warning messages:
* installing *source* package 'faahKO' ...
** R
** data
** inst
** preparing package for lazy loading
Warning in fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.13)
than is installed on your system (0.12.14). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
Error: package or namespace load failed for 'MSnbase' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'XML'
Error : package 'MSnbase' could not be loaded
ERROR: lazy loading failed for package 'faahKO'
* removing 'C:/Users/TANG Zhi/Documents/R/win-library/3.4/faahKO'
In R CMD INSTALL
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\TANG Zhi\Documents\R\win-library\3.4" "D:/Meta-tools/faahKO_1.19.0.tar.gz"' had status 1 
2: In install.packages(files[tarballs], .libPaths()[1L], repos = NULL,  :
  installation of package ‘D:/Meta-tools/faahKO_1.19.0.tar.gz’ had non-zero exit status

**Comment by wenbostar** [comment]
It looks like you don't have XML package installed, please install it in R using the following code:
```r
install.packages("XML")
```

**Comment by Tang17** [comment]
Yep, it works.
