### ISSUE TITLE
questions about QC-based batch correction implemented in metaX package

### ISSUE THREAD

**Issue by FSYtiredtodeath** [wenbostar/metaX#4]
After reading metaX article, metaX manual and R documentation for this package, I have two major questions on methods for QC-based batch correction implemented in metaX  R package.
1. In this package, i guess there are two functions to do QC-based batch correction in metaX, namely 'doQCRLSC()' and the 'qcsc' argument in 'metaXpipe()' . As described in metaX_manual, the function 'doQCRLSC()' is used for QC-RSC normalization; and the argument  'qcsc' contains values including   'none', 'QC-RLSC' and 'SVR'. As QC-RSC(Quality Control-Robust Spline Correction)  is a variation of QC-RLSC(Quality Control-Robust Loess Signal Correction) and they are obviously different methods, I wonder  if doQCRLSC() and 'QC-RLSC' in 'qcsc' argument mean the same or  different methods for  batch correction ?
2. If  doQCRLSC() and 'QC-RLSC' in 'qcsc' argument mean the same method, then which method of QC-RLSC and QC-RSC is used in this package?
Thanks a lot!

**Comment by wenbostar** [comment]
Hi @FSYtiredtodeath , the method implemented in doQCRLSC function is QC-RSC not QC-RLSC. I will update the description in the next version.

**Comment by wenbostar** [comment]
@FSYtiredtodeath , you're welcome. Please feel free to ask me if you have any questions about using metaX.

**Comment by renzhezhu677** [comment]
Hi @wenbostar , I have a questions on reference for pqn implemented in metaX R package.What is the reference used in pqn? QC samples or Samples？

**Comment by wenbostar** [comment]
Could you please open an new issue for this question?
