### ISSUE TITLE
can't export result of doQCRLSC() using getPeaksTable()

### ISSUE THREAD

**Issue by FSYtiredtodeath** [wenbostar/metaX#8]
Hi, here's my question about export the result of **doQCRLSC()**.
I used to normalize my intensity table using **metaX::normalize()** and export this result by **getPeaksTable()**. Here's my code:
```
para <- reSetPeaksData(para)
para <- metaX::normalize(para,method="pqn",valueID="value")
tab <- getPeaksTable(para, valueID = 'value')
write.table(tab, file = 'test.txt', quote = FALSE, sep = '\t')
```
However, when I tried to export the result of **doQCRLSC()**, I found the result of **doQCRLSC()** a table of batch and group information, without a corrected intensity table which is what I actually need. Also, running **doQCRLSC()** didn't cause any changes in **para@peaksData**. Therefore, can you show me the appropriate way to export QC-RLSC corrected data after performing **doQCRLSC()**? 
Thanks!

**Comment by wenbostar** [comment]
The function **doQCRLSC** will add a new column "valueNorm" into the para@peaksData data frame. So you can export the normalized intensity generated by **doQCRLSC** using the following method:

```
para <- doQCRLSC(...)
tab <- getPeaksTable(para, valueID = 'valueNorm')
```

**Comment by FSYtiredtodeath** [comment]
Thanks for your immediate reply! @wenbostar 
Actually, I checked the change in para@peaksData data frame before and after running the same code of **doQCRLSC** and **getPeaksTable** as you wrote in your reply, and I didn't find the new column "valueNorm" come out. Here's the output of **getPeaksTable**:
`> tab <- getPeaksTable(para, valueID = 'valueNorm')`
`value = valueNorm`
`Error: value.var (valueNorm) not found in input`
The version of my metaX package is 1.4.16. Would it be the problem from different version of metaX?

**Comment by wenbostar** [comment]
Could you please provide an reproducible example?

**Comment by FSYtiredtodeath** [comment]
Here's a my example using built-in data sample within metaX package:
```
library(metaX)
para <- new("metaXpara")
pfile <- system.file("extdata/MTBLS79.txt",package = "metaX")
sfile <- system.file("extdata/MTBLS79_sampleList.txt",package = "metaX")
rawPeaks(para) <- read.delim(pfile,check.names = FALSE)
sampleListFile(para) <- sfile
para <- reSetPeaksData(para)
res <- doQCRLSC(para,cpu=1, impute = FALSE)
tab <- getPeaksTable(para, valueID = 'valueNorm')
```
Notably, returned value of the function **doQCRLSC** was a list of CV summary before and after QC-RSC, so I chose to use another variable name ‘res’  in case the original 'para' was covered.

**Comment by FSYtiredtodeath** [comment]
Sorry to bother you again, but please let me know if I need to provide anything else for this example. @wenbostar

**Comment by wenbostar** [comment]
Sorry for the late reply. Below please find the right way to export the normalized data: 
```r
library(metaX)
para <- new("metaXpara")
pfile <- system.file("extdata/MTBLS79.txt",package = "metaX")
sfile <- system.file("extdata/MTBLS79_sampleList.txt",package = "metaX")
rawPeaks(para) <- read.delim(pfile,check.names = FALSE)
sampleListFile(para) <- sfile
para <- reSetPeaksData(para)
res <- doQCRLSC(para,cpu=1, impute = FALSE)
tab <- getPeaksTable(res$metaXpara, valueID = 'valueNorm')
```
