### ISSUE TITLE
metaX installation failed 

### ISSUE THREAD

**Issue by ElaineJiao** [wenbostar/metaX#9]
I try to install metaX package in the following two ways (windows platform), but they all failed. 

   1. download it from the http://metax.genomics.cn/. unzip it, and zip it into .tar. Then install from local package. 
    2. Using the following in Rstudio.
source("https://bioconductor.org/biocLite.R")
biocLite("wenbostar/metaX")

https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  无法载入共享目标对象‘C:/Program Files/R/R-3.4.3/library/KernSmooth/libs/x64/KernSmooth.dll’：:
  `已达到了DLL数目的上限...
ERROR: lazy loading failed for package 'metaX'
* removing 'C:/Program Files/R/R-3.4.3/library/metaX'
* restoring previous 'C:/Program Files/R/R-3.4.3/library/metaX'
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.4.3\library" "C:/Users/user/Desktop/R/metaX_1.4.16.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/user/Desktop/R/metaX_1.4.16.tar.gz’ had non-zero exit status.

Please help me fix this problem.

**Comment by wenbostar** [comment]
Please find a solution by looking at this issue #1 .
You can also upgrade your R to version 3.5.1 to fix this problem.
